CREATE TYPE PRIORITY_LEVEL AS ENUM('low', 'medium', 'high');

CREATE TABLE users (
    UserID VARCHAR(36) PRIMARY KEY,
    Username VARCHAR(50) UNIQUE NOT NULL,
    Password VARCHAR(50) NOT NULL
);

CREATE TABLE todos (
    TodoID VARCHAR(36) PRIMARY KEY,
    UserID VARCHAR(36) REFERENCES users(UserID),
    CreatedDate DATE NOT NULL,
    DueDate DATE,
    Info VARCHAR(1000),
    Priority PRIORITY_LEVEL NOT NULL
);

